/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    products: Product;
    media: Media;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  layout: (
    | HeroBlock
    | QuoteBlock
    | TimelineBlock
    | DualLoopBlock
    | ProductDemoBlock
    | ScaleStoryBlock
    | AboutBlock
    | FrameworkSectionBlock
    | FeatureGridBlock
    | ShowcaseBlock
    | WorkspaceBlock
    | AgentsBlock
    | PlatformCardsBlock
    | ProductGridBlock
    | RoadmapBlock
    | PricingBlock
    | NewsletterBlock
    | FAQBlock
    | CtaBlock
    | TestimonialsBlock
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  cta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  /**
   * One quiet line under the buttons, e.g. "Beta on macOS • iOS, watchOS and visionOS coming soon".
   */
  availabilityNote?: string | null;
  /**
   * Screenshot. Also acts as the poster frame when a video is set.
   */
  image?: (string | null) | Media;
  /**
   * Optional public image URL used when no upload is set.
   */
  assetUrl?: string | null;
  /**
   * Describe what the screen shows, for screen readers.
   */
  imageAlt?: string | null;
  /**
   * Optional MP4/WebM. Plays with visible controls — never autoplays.
   */
  video?: (string | null) | Media;
  /**
   * Optional public video URL used when no upload is set.
   */
  videoUrl?: string | null;
  /**
   * Short line under the media.
   */
  mediaCaption?: string | null;
  mediaFrame?: ('mac' | 'plain') | null;
  /**
   * Schematic drawn while this slot has no screenshot yet. Pick the one that matches the screen being described.
   */
  sketch?: ('workspace' | 'goal' | 'list' | 'matrix' | 'board' | 'calendar' | 'habits' | 'chart' | 'timeline') | null;
  /**
   * A second device standing in front of the desktop shot. Uncheck "Show" to render the Mac window alone — do that while the iPhone app is still unreleased rather than showing an invented screen.
   */
  phone?: {
    enabled?: boolean | null;
    /**
     * Portrait, 1179×2556 (iPhone) or similar. App content only, no device frame.
     */
    image?: (string | null) | Media;
    /**
     * Optional public URL used when no upload is set.
     */
    assetUrl?: string | null;
    imageAlt?: string | null;
    sketch?: ('list' | 'goal' | 'habits' | 'chart') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  /**
   * Legacy field. Not read by anything — the storage adapter now generates public URLs automatically. Safe to leave blank; kept only so existing values are not dropped.
   */
  r2Url?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  eyebrow?: string | null;
  statement: string;
  emphasis?: string | null;
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quoteBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  steps?:
    | {
        title: string;
        body?: string | null;
        eyebrow?: string | null;
        image?: (string | null) | Media;
        /**
         * Optional public Cloudflare R2 asset URL fallback.
         */
        assetUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * App screenshot for this section — e.g. the half-day rings. Falls back to the built-in time loop graphic when empty.
   */
  image?: (string | null) | Media;
  /**
   * Optional public image URL used when no upload is set.
   */
  assetUrl?: string | null;
  /**
   * Describe the image for screen readers.
   */
  imageAlt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timelineBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DualLoopBlock".
 */
export interface DualLoopBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  /**
   * One tab per brand. The first is selected by default.
   */
  tabs?:
    | {
        /**
         * e.g. TimeBite
         */
        label: string;
        /**
         * One line under the tab bar saying what this side does.
         */
        tagline?: string | null;
        /**
         * Chip and rail colour for this tab.
         */
        accent?: ('blue' | 'teal' | 'gold' | 'green' | 'pink' | 'lavender') | null;
        steps?:
          | {
              title: string;
              body?: string | null;
              /**
               * Leave blank when the stage simply exists. Available now = shipped. Beta = usable, in the private beta. In development = being built. Planned = committed, not started. Exploring = we are looking at it and nothing more.
               */
              status?: ('available' | 'beta' | 'in-development' | 'planned' | 'exploring') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dualLoopBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductDemoBlock".
 */
export interface ProductDemoBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  /**
   * Screenshot. Also acts as the poster frame when a video is set.
   */
  image?: (string | null) | Media;
  /**
   * Optional public image URL used when no upload is set.
   */
  assetUrl?: string | null;
  /**
   * Describe what the screen shows, for screen readers.
   */
  imageAlt?: string | null;
  /**
   * Optional MP4/WebM. Plays with visible controls — never autoplays.
   */
  video?: (string | null) | Media;
  /**
   * Optional public video URL used when no upload is set.
   */
  videoUrl?: string | null;
  /**
   * Short line under the media.
   */
  mediaCaption?: string | null;
  mediaFrame?: ('mac' | 'plain') | null;
  /**
   * Schematic drawn while this slot has no screenshot yet. Pick the one that matches the screen being described.
   */
  sketch?: ('workspace' | 'goal' | 'list' | 'matrix' | 'board' | 'calendar' | 'habits' | 'chart' | 'timeline') | null;
  /**
   * Shown beside the caption, e.g. "52 seconds".
   */
  duration?: string | null;
  /**
   * Plain-text walkthrough of what the video shows. Rendered in an expandable panel under the player — the accessible equivalent for anyone who cannot or would rather not watch.
   */
  transcript?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productDemoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScaleStoryBlock".
 */
export interface ScaleStoryBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  /**
   * Ordered smallest to largest — one action, then a day, and out to a year.
   */
  levels?:
    | {
        /**
         * e.g. ACTION, DAY, WEEK.
         */
        label: string;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  closingStatement?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'scaleStoryBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  wordParts?:
    | {
        part: string;
        meaning?: string | null;
        id?: string | null;
      }[]
    | null;
  closingStatement?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FrameworkSectionBlock".
 */
export interface FrameworkSectionBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  pillars?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  closingStatement?: string | null;
  cta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'frameworkSectionBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  /**
   * Drag to reorder — the order here is the order on the page.
   */
  items?:
    | {
        title: string;
        body?: string | null;
        eyebrow?: string | null;
        /**
         * Leave blank for a card with no badge. Anything unshipped must carry one. Available now = shipped. Beta = usable, in the private beta. In development = being built. Planned = committed, not started. Exploring = we are looking at it and nothing more.
         */
        status?: ('available' | 'beta' | 'in-development' | 'planned' | 'exploring') | null;
        /**
         * Screenshot. Also acts as the poster frame when a video is set.
         */
        image?: (string | null) | Media;
        /**
         * Optional public image URL used when no upload is set.
         */
        assetUrl?: string | null;
        /**
         * Describe what the screen shows, for screen readers.
         */
        imageAlt?: string | null;
        /**
         * Optional MP4/WebM. Plays with visible controls — never autoplays.
         */
        video?: (string | null) | Media;
        /**
         * Optional public video URL used when no upload is set.
         */
        videoUrl?: string | null;
        /**
         * Short line under the media.
         */
        mediaCaption?: string | null;
        mediaFrame?: ('mac' | 'plain') | null;
        /**
         * Schematic drawn while this slot has no screenshot yet. Pick the one that matches the screen being described.
         */
        sketch?:
          | ('workspace' | 'goal' | 'list' | 'matrix' | 'board' | 'calendar' | 'habits' | 'chart' | 'timeline')
          | null;
        /**
         * Uncheck to hide without deleting.
         */
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGridBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowcaseBlock".
 */
export interface ShowcaseBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  /**
   * Number the rows — use when the rows are a sequence rather than a set.
   */
  numbered?: boolean | null;
  rows?:
    | {
        title: string;
        body?: string | null;
        /**
         * Badge on the step. Leave blank when the step is simply shipped and obvious. Available now = shipped. Beta = usable, in the private beta. In development = being built. Planned = committed, not started. Exploring = we are looking at it and nothing more.
         */
        status?: ('available' | 'beta' | 'in-development' | 'planned' | 'exploring') | null;
        /**
         * Screenshot. Also acts as the poster frame when a video is set.
         */
        image?: (string | null) | Media;
        /**
         * Optional public image URL used when no upload is set.
         */
        assetUrl?: string | null;
        /**
         * Describe what the screen shows, for screen readers.
         */
        imageAlt?: string | null;
        /**
         * Optional MP4/WebM. Plays with visible controls — never autoplays.
         */
        video?: (string | null) | Media;
        /**
         * Optional public video URL used when no upload is set.
         */
        videoUrl?: string | null;
        /**
         * Short line under the media.
         */
        mediaCaption?: string | null;
        mediaFrame?: ('mac' | 'plain') | null;
        /**
         * Schematic drawn while this slot has no screenshot yet. Pick the one that matches the screen being described.
         */
        sketch?:
          | ('workspace' | 'goal' | 'list' | 'matrix' | 'board' | 'calendar' | 'habits' | 'chart' | 'timeline')
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'showcaseBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkspaceBlock".
 */
export interface WorkspaceBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  modules?:
    | {
        name: string;
        description?: string | null;
        /**
         * Components are TimeBite surfaces — Today, Actions, Calendar. Goal areas are Creating Your Reality life domains — Career, Fitness, Finance. They are grouped separately because they are different things: one is a view, the other is a part of your life.
         */
        kind: 'component' | 'goal-area';
        sketch?: ('list' | 'goal' | 'matrix' | 'board' | 'calendar' | 'habits' | 'chart' | 'timeline') | null;
        /**
         * Available now = shipped. Beta = usable, in the private beta. In development = being built. Planned = committed, not started. Exploring = we are looking at it and nothing more.
         */
        status?: ('available' | 'beta' | 'in-development' | 'planned' | 'exploring') | null;
        /**
         * Starts switched on in the demo workspace.
         */
        defaultOn?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The sample agent suggestion. Leave the prompt blank to hide the card.
   */
  suggestion?: {
    /**
     * Which agent is speaking, e.g. "Goal Agent".
     */
    source?: string | null;
    prompt?: string | null;
    /**
     * Name of the widget it offers to add.
     */
    moduleName?: string | null;
    sketch?: ('chart' | 'timeline' | 'goal' | 'board') | null;
    acceptLabel?: string | null;
    dismissLabel?: string | null;
    /**
     * Shown after "Not now" — keep it unbothered.
     */
    dismissedNote?: string | null;
  };
  footnote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'workspaceBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgentsBlock".
 */
export interface AgentsBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  agents?:
    | {
        name: string;
        body?: string | null;
        /**
         * Available now = shipped. Beta = usable, in the private beta. In development = being built. Planned = committed, not started. Exploring = we are looking at it and nothing more.
         */
        status?: ('available' | 'beta' | 'in-development' | 'planned' | 'exploring') | null;
        /**
         * Outcomes, phrased as things it does for you.
         */
        capabilities?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Scope limit shown in the card, e.g. the Finance Agent boundary.
         */
        disclaimer?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Points at the public roadmap and changelog. Hidden until a URL is set, so it never renders a dead button. For reference, Sunsama runs theirs on Canny at roadmap.sunsama.com — that is the obvious option if you want feedback voting alongside a changelog.
   */
  roadmapCta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  footnote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'agentsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlatformCardsBlock".
 */
export interface PlatformCardsBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  platforms?:
    | {
        title: string;
        body?: string | null;
        /**
         * Available now = shipped. Beta = usable, in the private beta. In development = being built. Planned = committed, not started. Exploring = we are looking at it and nothing more.
         */
        status?: ('available' | 'beta' | 'in-development' | 'planned' | 'exploring') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'platformCardsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridBlock".
 */
export interface ProductGridBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  /**
   * Leave empty to show every product marked "Show on the site", ordered by its sort order. Pick products here to show only those, in the order you choose.
   */
  products?: (string | Product)[] | null;
  cta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  /**
   * Small print under the grid, e.g. that nothing is charged yet.
   */
  footnote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productGridBlock';
}
/**
 * Planners, pads and stationery. Shown on the homepage by the "Physical Product Grid" block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * e.g. Planner, Task & Time, Goal Notes.
   */
  name: string;
  /**
   * Lowercase, hyphenated, unique. Used for future product pages and links, e.g. task-and-time.
   */
  slug: string;
  /**
   * One or two sentences. This is what appears on the card.
   */
  description?: string | null;
  productType?: ('planner' | 'pad' | 'notes' | 'tools' | 'other') | null;
  /**
   * Optional line under the name, e.g. "Quarterly · Annual · Undated".
   */
  variantNote?: string | null;
  /**
   * Concept = an idea we are showing. Sample = physically prototyped. Preorder = taking orders. Available = shipping. Sold out = none left. Nothing may say "available" until it actually ships.
   */
  status: 'concept' | 'sample' | 'preorder' | 'available' | 'sold-out';
  /**
   * Uploaded through Media, so they go to Cloudflare R2 when R2 is enabled. The first image is the one shown on the card.
   */
  images?:
    | {
        image: string | Media;
        /**
         * Overrides the alt text set on the Media item.
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Number only, no currency symbol, e.g. 35.55. Leave blank while pricing is undecided.
   */
  price?: string | null;
  /**
   * Optional. Shown struck through beside the price.
   */
  compareAtPrice?: string | null;
  /**
   * Leave the label blank to render the card without a button.
   */
  cta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Gives the card the highlighted treatment.
   */
  featured?: boolean | null;
  /**
   * Uncheck to keep a product configured but hidden, without deleting it.
   */
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoadmapBlock".
 */
export interface RoadmapBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  highlights?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Link to the external roadmap board. Hidden until a URL is set.
   */
  cta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'roadmapBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  cta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  /**
   * Free trial line above the plans, e.g. "Try TimeBite free for 30 days."
   */
  trialCopy?: string | null;
  digitalEyebrow?: string | null;
  monthlyLabel?: string | null;
  annualLabel?: string | null;
  /**
   * Small badge beside the annual toggle, e.g. "Best value".
   */
  annualBadge?: string | null;
  digitalPlans?:
    | {
        name: string;
        /**
         * Number only, no currency symbol. Use "0" for free. Blank if not sold monthly.
         */
        monthlyPrice?: string | null;
        /**
         * Number only, no currency symbol. Blank if not sold annually.
         */
        annualPrice?: string | null;
        /**
         * Shown only on the annual view, e.g. "Two months free against paying monthly."
         */
        annualNote?: string | null;
        description?: string | null;
        badge?: string | null;
        featured?: boolean | null;
        features?:
          | {
              text: string;
              /**
               * Tags an unshipped line so availability never has to be written into the text itself. Available now = shipped. Beta = usable, in the private beta. In development = being built. Planned = committed, not started. Exploring = we are looking at it and nothing more.
               */
              status?: ('available' | 'beta' | 'in-development' | 'planned' | 'exploring') | null;
              id?: string | null;
            }[]
          | null;
        cta?: {
          label?: string | null;
          /**
           * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
           */
          url?: string | null;
          /**
           * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
           */
          newTab?: boolean | null;
          /**
           * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
           */
          analyticsId?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Invite-code promotion. The code itself is never rendered — redemption belongs to the billing provider.
   */
  betaPromotion?: {
    enabled?: boolean | null;
    label?: string | null;
    body?: string | null;
    cta?: {
      label?: string | null;
      /**
       * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
       */
      url?: string | null;
      /**
       * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
       */
      newTab?: boolean | null;
      /**
       * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
       */
      analyticsId?: string | null;
    };
  };
  /**
   * One line about cross-device access. Device status lives in the Platform Cards block.
   */
  platformNote?: {
    text?: string | null;
    cta?: {
      label?: string | null;
      /**
       * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
       */
      url?: string | null;
      /**
       * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
       */
      newTab?: boolean | null;
      /**
       * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
       */
      analyticsId?: string | null;
    };
  };
  footnote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  cta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  formNote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletterBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  cta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  eyebrow?: string | null;
  headline: string;
  body?: string | null;
  items?:
    | {
        quote: string;
        author: string;
        role?: string | null;
        company?: string | null;
        avatar?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsBlock';
}
/**
 * Written posts. Shown at /blog, newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * Lowercase and hyphenated. The URL becomes /blog/<slug>.
   */
  slug: string;
  /**
   * One or two sentences shown on the blog index and used as the SEO description when none is set.
   */
  excerpt?: string | null;
  /**
   * Shown on the card and at the top of the post. Landscape, 1600×900 or larger. Uploaded through Media, so it goes to R2.
   */
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('intentional-living' | 'planning' | 'building' | 'career' | 'notes') | null;
  /**
   * Controls ordering on the index. Leave blank and it fills in on publish.
   */
  publishedAt?: string | null;
  /**
   * Optional. Shown beside the date. Leave blank to hide it.
   */
  readingMinutes?: number | null;
  /**
   * Link to this post on Substack. When set, the end of the post shows "Read this on Substack" automatically — you never type that line yourself. Leave blank to fall back to the site-wide Substack link.
   */
  substackUrl?: string | null;
  /**
   * Pins this post to the top of the index.
   */
  featured?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroBlock?: T | HeroBlockSelect<T>;
        quoteBlock?: T | QuoteBlockSelect<T>;
        timelineBlock?: T | TimelineBlockSelect<T>;
        dualLoopBlock?: T | DualLoopBlockSelect<T>;
        productDemoBlock?: T | ProductDemoBlockSelect<T>;
        scaleStoryBlock?: T | ScaleStoryBlockSelect<T>;
        aboutBlock?: T | AboutBlockSelect<T>;
        frameworkSectionBlock?: T | FrameworkSectionBlockSelect<T>;
        featureGridBlock?: T | FeatureGridBlockSelect<T>;
        showcaseBlock?: T | ShowcaseBlockSelect<T>;
        workspaceBlock?: T | WorkspaceBlockSelect<T>;
        agentsBlock?: T | AgentsBlockSelect<T>;
        platformCardsBlock?: T | PlatformCardsBlockSelect<T>;
        productGridBlock?: T | ProductGridBlockSelect<T>;
        roadmapBlock?: T | RoadmapBlockSelect<T>;
        pricingBlock?: T | PricingBlockSelect<T>;
        newsletterBlock?: T | NewsletterBlockSelect<T>;
        faqBlock?: T | FAQBlockSelect<T>;
        ctaBlock?: T | CtaBlockSelect<T>;
        testimonialsBlock?: T | TestimonialsBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  availabilityNote?: T;
  image?: T;
  assetUrl?: T;
  imageAlt?: T;
  video?: T;
  videoUrl?: T;
  mediaCaption?: T;
  mediaFrame?: T;
  sketch?: T;
  phone?:
    | T
    | {
        enabled?: T;
        image?: T;
        assetUrl?: T;
        imageAlt?: T;
        sketch?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  statement?: T;
  emphasis?: T;
  attribution?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        eyebrow?: T;
        image?: T;
        assetUrl?: T;
        id?: T;
      };
  image?: T;
  assetUrl?: T;
  imageAlt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DualLoopBlock_select".
 */
export interface DualLoopBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  tabs?:
    | T
    | {
        label?: T;
        tagline?: T;
        accent?: T;
        steps?:
          | T
          | {
              title?: T;
              body?: T;
              status?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductDemoBlock_select".
 */
export interface ProductDemoBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  image?: T;
  assetUrl?: T;
  imageAlt?: T;
  video?: T;
  videoUrl?: T;
  mediaCaption?: T;
  mediaFrame?: T;
  sketch?: T;
  duration?: T;
  transcript?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScaleStoryBlock_select".
 */
export interface ScaleStoryBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  levels?:
    | T
    | {
        label?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  closingStatement?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  wordParts?:
    | T
    | {
        part?: T;
        meaning?: T;
        id?: T;
      };
  closingStatement?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FrameworkSectionBlock_select".
 */
export interface FrameworkSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  pillars?:
    | T
    | {
        label?: T;
        id?: T;
      };
  closingStatement?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        eyebrow?: T;
        status?: T;
        image?: T;
        assetUrl?: T;
        imageAlt?: T;
        video?: T;
        videoUrl?: T;
        mediaCaption?: T;
        mediaFrame?: T;
        sketch?: T;
        enabled?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowcaseBlock_select".
 */
export interface ShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  numbered?: T;
  rows?:
    | T
    | {
        title?: T;
        body?: T;
        status?: T;
        image?: T;
        assetUrl?: T;
        imageAlt?: T;
        video?: T;
        videoUrl?: T;
        mediaCaption?: T;
        mediaFrame?: T;
        sketch?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkspaceBlock_select".
 */
export interface WorkspaceBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  modules?:
    | T
    | {
        name?: T;
        description?: T;
        kind?: T;
        sketch?: T;
        status?: T;
        defaultOn?: T;
        id?: T;
      };
  suggestion?:
    | T
    | {
        source?: T;
        prompt?: T;
        moduleName?: T;
        sketch?: T;
        acceptLabel?: T;
        dismissLabel?: T;
        dismissedNote?: T;
      };
  footnote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgentsBlock_select".
 */
export interface AgentsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  agents?:
    | T
    | {
        name?: T;
        body?: T;
        status?: T;
        capabilities?:
          | T
          | {
              text?: T;
              id?: T;
            };
        disclaimer?: T;
        id?: T;
      };
  roadmapCta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  footnote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlatformCardsBlock_select".
 */
export interface PlatformCardsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  platforms?:
    | T
    | {
        title?: T;
        body?: T;
        status?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridBlock_select".
 */
export interface ProductGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  products?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  footnote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoadmapBlock_select".
 */
export interface RoadmapBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  highlights?:
    | T
    | {
        label?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  trialCopy?: T;
  digitalEyebrow?: T;
  monthlyLabel?: T;
  annualLabel?: T;
  annualBadge?: T;
  digitalPlans?:
    | T
    | {
        name?: T;
        monthlyPrice?: T;
        annualPrice?: T;
        annualNote?: T;
        description?: T;
        badge?: T;
        featured?: T;
        features?:
          | T
          | {
              text?: T;
              status?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
        id?: T;
      };
  betaPromotion?:
    | T
    | {
        enabled?: T;
        label?: T;
        body?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
      };
  platformNote?:
    | T
    | {
        text?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              analyticsId?: T;
            };
      };
  footnote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock_select".
 */
export interface NewsletterBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  formNote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  body?: T;
  items?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        company?: T;
        avatar?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  category?: T;
  publishedAt?: T;
  readingMinutes?: T;
  substackUrl?: T;
  featured?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  productType?: T;
  variantNote?: T;
  status?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  price?: T;
  compareAtPrice?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  sortOrder?: T;
  featured?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  r2Url?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logoText?: string | null;
  logoTag?: string | null;
  navLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  brandStatement?: string | null;
  explore: {
    title: string;
    links?:
      | {
          label: string;
          url?: string | null;
          /**
           * Renders as a disabled label instead of a link when no page exists yet.
           */
          comingSoon?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  product: {
    title: string;
    links?:
      | {
          label: string;
          url?: string | null;
          /**
           * Renders as a disabled label instead of a link when no page exists yet.
           */
          comingSoon?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  comingSoon: {
    title: string;
    links?:
      | {
          label: string;
          url?: string | null;
          /**
           * Renders as a disabled label instead of a link when no page exists yet.
           */
          comingSoon?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  learn: {
    title: string;
    links?:
      | {
          label: string;
          url?: string | null;
          /**
           * Renders as a disabled label instead of a link when no page exists yet.
           */
          comingSoon?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  company: {
    title: string;
    links?:
      | {
          label: string;
          url?: string | null;
          /**
           * Renders as a disabled label instead of a link when no page exists yet.
           */
          comingSoon?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  social: {
    title: string;
    links?:
      | {
          label: string;
          url?: string | null;
          /**
           * Renders as a disabled label instead of a link when no page exists yet.
           */
          comingSoon?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * e.g. "© Creating Your Reality. All rights reserved."
   */
  legalNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  brandName?: string | null;
  organizationName?: string | null;
  siteTagline?: string | null;
  brandDescription?: string | null;
  productDescription?: string | null;
  openGraphDescription?: string | null;
  headerTag?: string | null;
  footerBrandStatement?: string | null;
  /**
   * The site-wide default for the beta button. Blocks that set their own button override this; blocks that leave it blank fall back to here. This is the one place to change where "Join the TimeBite Beta" points.
   */
  betaCta?: {
    label?: string | null;
    /**
     * Internal path (/philosophy), on-page anchor (#beta), or a full external URL (https://…).
     */
    url?: string | null;
    /**
     * Turn on for links that leave the site, such as Substack. Adds rel="noopener noreferrer".
     */
    newTab?: boolean | null;
    /**
     * Optional. Rendered as data-analytics-event so this button can be tracked, e.g. join_beta_hero.
     */
    analyticsId?: string | null;
  };
  /**
   * Superseded by "Beta call to action" above. Kept so existing values are not dropped.
   */
  betaButtonLabel?: string | null;
  substackButtonLabel?: string | null;
  notFoundCtaLabel?: string | null;
  legalNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logoText?: T;
  logoTag?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandStatement?: T;
  explore?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              comingSoon?: T;
              id?: T;
            };
      };
  product?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              comingSoon?: T;
              id?: T;
            };
      };
  comingSoon?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              comingSoon?: T;
              id?: T;
            };
      };
  learn?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              comingSoon?: T;
              id?: T;
            };
      };
  company?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              comingSoon?: T;
              id?: T;
            };
      };
  social?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              comingSoon?: T;
              id?: T;
            };
      };
  legalNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  organizationName?: T;
  siteTagline?: T;
  brandDescription?: T;
  productDescription?: T;
  openGraphDescription?: T;
  headerTag?: T;
  footerBrandStatement?: T;
  betaCta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        analyticsId?: T;
      };
  betaButtonLabel?: T;
  substackButtonLabel?: T;
  notFoundCtaLabel?: T;
  legalNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}